# 0. Imports

In [1]:
import pandas as pd
from scrapper import elo_rating

# 1. Read Multiple Dates

The scrapper works on yearly ratings. It is possible to choose the year of interest. I decided for the year before World Cup.

In [2]:
df_rating_year_before_cup = elo_rating.get_elo_rating(dates=[1993, 1997, 2001, 2005, 2009, 2013, 2017, 2021])

In [4]:
df_rating_year_before_cup

,RK,Team,Rating,AverageRank,AverageRating,YearRank,YearRating,MatchesTotal,MathcesHome,MatchesAway,MatchesNeutral,MatchesWins,MatchesLosses,MatchesDraws,GoalsFor,GoalsAgainst
Year,,,,,,,,,,,,,,,,
1993,1,Germany,2015,9,1883,+2,+21,612,269,261,82,343,145,124,1378,786
1993,2,Italy,2000,8,1901,+2,+20,507,246,192,69,270,107,130,942,557
1993,3,Netherlands,1995,18,1798,+2,+27,512,246,219,47,238,170,104,1075,802
1993,4,Brazil,1950,5,1975,−2,−49,590,244,192,154,359,108,123,1270,608
1993,5,Yugoslavia,1933,19,1775,+2,0,523,192,253,78,252,169,102,1097,816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021,235,Tonga,528,210,665,0,0,62,8,14,40,14,42,6,70,242
2021,236,Niue,496,222,496,0,0,2,0,0,2,0,2,0,0,33
2021,237,Eastern Samoa,472,222,473,0,0,51,0,13,38,4,45,2,30,340
2021,238,Northern Marianas,409,229,528,0,0,26,3,9,14,3,21,2,31,116
2021,239,Palau,403,233,403,0,0,2,2,0,0,0,2,0,3,27

# 2. Saving into CSV

In [5]:
df_rating_year_before_cup.to_csv('./datasets/elo_rating.csv')